USE [trazaweb]
GO
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Administrar Agentes', 'Muestra la página de administración de Agentes', 'Agente', 'ar.com.mbsoftsa.trazabilidad.domain.Agente', 'ROLE_ADMINISTRAR_AGENTE', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Actualizar Agente', 'Actualizar Agente', 'Agente', 'ar.com.mbsoftsa.trazabilidad.domain.Agente', 'ROLE_ACTUALIZAR_AGENTE', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Borrar Agente', 'Elimina un Agente', 'Agente', 'ar.com.mbsoftsa.trazabilidad.domain.Agente', 'ROLE_BORRAR_AGENTE', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Agregar Agente', 'Agrega un Agente', 'Agente', 'ar.com.mbsoftsa.trazabilidad.domain.Agente', 'ROLE_AGREGAR_AGENTE', 1)
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Recuperar detalle de Movimiento', 'Recupera los detalles de Movimiento', 'Movimiento', 'ar.com.mbsoftsa.trazabilidad.domain.Movimiento', 'ROLE_RECUPERAR_MOVIMIENTO', 0);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Administrar Movimiento', 'Muestra la página de administración de Movimientos', 'Movimiento', 'ar.com.mbsoftsa.trazabilidad.domain.Movimiento', 'ROLE_ADMINISTRAR_MOVIMIENTO', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Actualizar Movimiento', 'Actualizar Movimiento', 'Movimiento', 'ar.com.mbsoftsa.trazabilidad.domain.Movimiento', 'ROLE_ACTUALIZAR_MOVIMIENTO', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Borrar Movimiento', 'Elimina un Movimiento', 'Movimiento', 'ar.com.mbsoftsa.trazabilidad.domain.Movimiento', 'ROLE_BORRAR_MOVIMIENTO', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Agregar Movimiento', 'Agrega un Movimiento', 'Movimiento', 'ar.com.mbsoftsa.trazabilidad.domain.Movimiento', 'ROLE_AGREGAR_MOVIMIENTO', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Recuperar Cancelacion', 'Recupera los detalles de Cancelaciones', 'Cancelacion', 'ar.com.mbsoftsa.trazabilidad.domain.Cancelacion', 'ROLE_RECUPERAR_CANCELACION', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Administrar Cancelacion', 'Muetras la página de administracion de Cancelaciones', 'Cancelacion', 'ar.com.mbsoftsa.trazabilidad.domain.Cancelacion', 'ROLE_ADMINISTRAR_CANCELACION', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Actualizar Cancelacion', 'Actualizar Cancelacion', 'Cancelacion', 'ar.com.mbsoftsa.trazabilidad.domain.Cancelacion', 'ROLE_ACTUALIZAR_CANCELACION', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Borrar Cancelacion', 'Elimina un Cancelacion', 'Cancelacion', 'ar.com.mbsoftsa.trazabilidad.domain.Cancelacion', 'ROLE_BORRAR_CANCELACION', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Agregar Cancelacion', 'Agrega un Cancelacion', 'Cancelacion', 'ar.com.mbsoftsa.trazabilidad.domain.Cancelacion', 'ROLE_AGREGAR_CANCELACION', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Recuperar detalle de Envio', 'Recupera los detalles de Envio', 'Envio', 'ar.com.mbsoftsa.trazabilidad.domain.Envio', 'ROLE_RECUPERAR_ENVIO', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Actualizar Envio', 'Actualiza Envio', 'Envio', 'ar.com.mbsoftsa.trazabilidad.domain.Envio', 'ROLE_ACTUALIZAR_ENVIO', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Borrar Envio', 'Elimina un Envio', 'Envio', 'ar.com.mbsoftsa.trazabilidad.domain.Envio', 'ROLE_BORRAR_ENVIO', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Agregar Envio', 'Agrega un Envio', 'Envio', 'ar.com.mbsoftsa.trazabilidad.domain.Envio', 'ROLE_AGREGAR_ENVIO', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Borrar Error', 'Elimina un Error', 'WSError', 'ar.com.mbsoftsa.trazabilidad.domain.WSError', 'ROLE_BORRAR_ERROR', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Administrar Usuario Web Service', 'Muestra la página de administración de Usuario Web Service', 'WSUser', 'ar.com.mbsoftsa.trazabilidad.domain.WSUser', 'ROLE_ADMINISTRAR_WSUSER', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Actualizar Usuario Web Service', 'Actualiza Usuario Web Service', 'WSUser', 'ar.com.mbsoftsa.trazabilidad.domain.WSUser', 'ROLE_ACTUALIZAR_WSUSER', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Administrar Tipo Agente', 'Muestra la página de administración de Tipo Agente', 'TipoAgente', 'ar.com.mbsoftsa.trazabilidad.domain.TipoAgente', 'ROLE_ADMINISTRAR_TIPOAGENTE', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Actualizar Tipo Agente', 'Actualiza un Tipo Agente', 'TipoAgente', 'ar.com.mbsoftsa.trazabilidad.domain.TipoAgente', 'ROLE_ACTUALIZAR_TIPOAGENTE', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Borrar Tipo Agente', 'Elimina un Tipo Agente', 'TipoAgente', 'ar.com.mbsoftsa.trazabilidad.domain.TipoAgente', 'ROLE_BORRAR_TIPOAGENTE', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Agregar Tipo Agente', 'Agrega un Tipo Agente', 'TipoAgente', 'ar.com.mbsoftsa.trazabilidad.domain.TipoAgente', 'ROLE_AGREGAR_TIPOAGENTE', 1)
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Administrar Evento', 'Muestra la página de administración de Evento', 'Evento', 'ar.com.mbsoftsa.trazabilidad.domain.Evento', 'ROLE_ADMINISTRAR_EVENTO', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Actualizar Evento', 'Actualiza un Evento', 'Evento', 'ar.com.mbsoftsa.trazabilidad.domain.Evento', 'ROLE_ACTUALIZAR_EVENTO', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Borrar Evento', 'Elimina un Evento', 'Evento', 'ar.com.mbsoftsa.trazabilidad.domain.Evento', 'ROLE_BORRAR_EVENTO', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Agregar Evento', 'Agrega un Evento', 'Evento', 'ar.com.mbsoftsa.trazabilidad.domain.Evento', 'ROLE_AGREGAR_EVENTO', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Administrar Medicamento', 'Muestra la página de administración de Medicamento', 'Medicamento', 'ar.com.mbsoftsa.trazabilidad.domain.Medicamento', 'ROLE_ADMINISTRAR_MEDICAMENTO', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Actualizar Medicamento', 'Actualiza un Medicamento', 'Medicamento', 'ar.com.mbsoftsa.trazabilidad.domain.Medicamento', 'ROLE_ACTUALIZAR_MEDICAMENTO', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Borrar Medicamento', 'Elimina un Medicamento', 'Medicamento', 'ar.com.mbsoftsa.trazabilidad.domain.Medicamento', 'ROLE_BORRAR_MEDICAMENTO', 1);
INSERT INTO [trazaweb].[TS_PERMISO] ([PERSISTENT_VERSION], [NOMBRE], [DESCRIPCION], [ENTIDAD], [CLASE_ENTIDAD], [AUTHORITY_NAME], [AUDITABLE]) VALUES (0, 'Agregar Medicamento', 'Agrega un Medicamento', 'Medicamento', 'ar.com.mbsoftsa.trazabilidad.domain.Medicamento', 'ROLE_AGREGAR_MEDICAMENTO', 1)

GO